config/routes.rb
GoogleScholarTragger::Application.routes.draw do
  
  resources :tasks

  resources :users, only: [:show, :index, :create, :new, :destroy]

  resources :query_clicks, only: [:create]

  resources :scholar_queries, only: [:create, :destroy, :show, :index]

  post "/zip/:user_id", to: "users#download_zip"
 
  get "/login", to: "users#admin_login"
  post "/download_user_data", to: "users#download_data"
  get "/", to: "users#admin_login"
  post "/login", to: "users#admin_login_check"
  post "/logout", to: "users#admin_logout"

  get "/search/:token", to: "api#user_search"
  post "/query", to: "api#scholar_query"
  
  post "/feedback", to: "scholar_queries#feedback"
  get "/download_query_clicks/:query_id", to: "scholar_queries#download_clicks_timings"
  get "/download_query_scroll_behavior/:query_id", to: "scholar_queries#download_scroll_behavior"

  post "/query_scroll", to: "query_scrolls#create"

  post "/task_reports", to: "task_reports#create"
  post "/send_task_report", to: "task_reports#update"
  post "/download_task_report/:task_report_id", to: "task_reports#download_task_report"
  delete "/task_reports/:id", to: "task_reports#destroy"

  get "/users_tasks", to: "tasks#users_tasks"

  post "/query_click_end", to: "query_clicks#query_click_end"

end

app/models/query_click.rb
class QueryClick < ActiveRecord::Base
	belongs_to :scholar_query

	def duration
		if end_time.nil?
			return "[No end time]"
		else
			return end_time - created_at
		end
	end
end

app/controllers/query_clicks_controller.rb
class QueryClicksController < ApplicationController
  before_action :set_query_click, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:create]

  # GET /query_clicks
  # GET /query_clicks.json
  def index
    @query_clicks = QueryClick.all
  end

  # GET /query_clicks/1
  # GET /query_clicks/1.json
  def show
  end

  # GET /query_clicks/new
  def new
    @query_click = QueryClick.new
  end

  # GET /query_clicks/1/edit
  def edit
  end

  # POST /query_clicks
  # POST /query_clicks.json
  def create
    query_click = QueryClick.new(scholar_query_id: params[:scholar_query_id], heading: params[:heading], synopsis: params[:synopsis], link_location: params[:link_location], sitations: params[:sitations], location: params[:location], authors: params[:authors], click_time: params[:click_time])
    query_click.save

    render json: { id: query_click.id }
  end

  def query_click_end
    query_click = QueryClick.find(params[:id])
    query_click.end_time = Time.now
    query_click.save
  end

  # PATCH/PUT /query_clicks/1
  # PATCH/PUT /query_clicks/1.json
  def update
    respond_to do |format|
      if @query_click.update(query_click_params)
        format.html { redirect_to @query_click, notice: 'Query click was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @query_click.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /query_clicks/1
  # DELETE /query_clicks/1.json
  def destroy
    @query_click.destroy
    respond_to do |format|
      format.html { redirect_to query_clicks_url }
      format.json { head :no_content }
    end
  end

  private

    def check_user
      if not is_user?
        redirect_to "/login"
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_query_click
      @query_click = QueryClick.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def query_click_params
      params.require(:query_click).permit(:scholar_query_id, :heading, :synopsis, :link_location, :sitations, :location)
    end
end

app/helpers/query_clicks_helper.rb
module QueryClicksHelper
end

app/views/query_clicks/_form.html.erb
<%= form_for(@query_click) do |f| %>
  <% if @query_click.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@query_click.errors.count, "error") %> prohibited this query_click from being saved:</h2>

      <ul>
      <% @query_click.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :scholar_query_id %><br>
    <%= f.number_field :scholar_query_id %>
  </div>
  <div class="field">
    <%= f.label :heading %><br>
    <%= f.text_area :heading %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br>
    <%= f.text_area :synopsis %>
  </div>
  <div class="field">
    <%= f.label :link_location %><br>
    <%= f.text_field :link_location %>
  </div>
  <div class="field">
    <%= f.label :sitations %><br>
    <%= f.text_field :sitations %>
  </div>
  <div class="field">
    <%= f.label :click_time %><br>
    <%= f.datetime_select :click_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/query_clicks/edit.html.erb
<h1>Editing query_click</h1>

<%= render 'form' %>

<%= link_to 'Show', @query_click %> |
<%= link_to 'Back', query_clicks_path %>

app/views/query_clicks/index.html.erb
<h1>Listing query_clicks</h1>

<table>
  <thead>
    <tr>
      <th>Scholar query</th>
      <th>Heading</th>
      <th>Synopsis</th>
      <th>Link location</th>
      <th>Sitations</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @query_clicks.each do |query_click| %>
      <tr>
        <td><%= query_click.scholar_query_id %></td>
        <td><%= query_click.heading %></td>
        <td><%= query_click.synopsis %></td>
        <td><%= query_click.link_location %></td>
        <td><%= query_click.sitations %></td>
        <td><%= link_to 'Show', query_click %></td>
        <td><%= link_to 'Edit', edit_query_click_path(query_click) %></td>
        <td><%= link_to 'Destroy', query_click, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Query click', new_query_click_path %>

app/views/query_clicks/new.html.erb
<h1>New query_click</h1>

<%= render 'form' %>

<%= link_to 'Back', query_clicks_path %>

app/views/query_clicks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Scholar query:</strong>
  <%= @query_click.scholar_query_id %>
</p>

<p>
  <strong>Heading:</strong>
  <%= @query_click.heading %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @query_click.synopsis %>
</p>

<p>
  <strong>Link location:</strong>
  <%= @query_click.link_location %>
</p>

<p>
  <strong>Sitations:</strong>
  <%= @query_click.sitations %>
</p>

<p>
  <strong>Click time:</strong>
  <%= @query_click.click_time %>
</p>

<%= link_to 'Edit', edit_query_click_path(@query_click) %> |
<%= link_to 'Back', query_clicks_path %>