config/routes.rb
GoogleScholarTragger::Application.routes.draw do
  
  resources :tasks

  resources :users, only: [:show, :index, :create, :new, :destroy]

  resources :query_clicks, only: [:create]

  resources :scholar_queries, only: [:create, :destroy, :show, :index]

  post "/zip/:user_id", to: "users#download_zip"
 
  get "/login", to: "users#admin_login"
  post "/download_user_data", to: "users#download_data"
  get "/", to: "users#admin_login"
  post "/login", to: "users#admin_login_check"
  post "/logout", to: "users#admin_logout"

  get "/search/:token", to: "api#user_search"
  post "/query", to: "api#scholar_query"
  
  post "/feedback", to: "scholar_queries#feedback"
  get "/download_query_clicks/:query_id", to: "scholar_queries#download_clicks_timings"
  get "/download_query_scroll_behavior/:query_id", to: "scholar_queries#download_scroll_behavior"

  post "/query_scroll", to: "query_scrolls#create"

  post "/task_reports", to: "task_reports#create"
  post "/send_task_report", to: "task_reports#update"
  post "/download_task_report/:task_report_id", to: "task_reports#download_task_report"
  delete "/task_reports/:id", to: "task_reports#destroy"

  get "/users_tasks", to: "tasks#users_tasks"

  post "/query_click_end", to: "query_clicks#query_click_end"

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :task_reports, dependent: :destroy
	has_many :scholar_queries, dependent: :destroy
	
	validates :name, uniqueness: true, presence: true

	def get_url
		return "/search/#{token}"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include DataFormatter

  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :check_admin, only: [:show, :destroy, :new, :create, :index, :download_data]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.includes(task_reports: [:task, :scholar_queries]).find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
  
    token = (0...6).map { ('a'..'z').to_a[rand(26)] }.join
    until(User.all.find_by_token(token).nil?)
      token = (0...6).map { ('a'..'z').to_a[rand(26)] }.join
    end

    @user = User.new(name: params[:user][:name], token: token)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end

  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def download_zip
    user = User.find(params[:user_id])

    if(params[:content] == 'clicks_no_time')
      clicks_no_time_zip(user)
    elsif(params[:content] == 'clicks_with_time')
      clicks_with_time_zip(user)
    elsif(params[:content] == 'queries')
      queries_zip(user)
    elsif(params[:content] == 'scroll')
      scroll_zip(user)
    else
      summaries_zip(user)
    end
  end

  def download_data

    user = User.find(params[:user_id])

    if(params[:include] == "query_clicks_and_timings")
      send_data(get_query_clicks_data(params[:user_id], true), filename: "#{user.name.gsub(/\s+/, "_")}_data.csv")
    elsif(params[:include] == "query_clicks")
      send_data(get_query_clicks_data(params[:user_id], false), filename: "#{user.name.gsub(/\s+/, "_")}_data.csv")
    elsif(params[:include] == "query_scroll_behavior")
      send_data(get_query_scroll_behavior(params[:user_id]), filename: "#{user.name.gsub(/\s+/, "_")}_data.csv")
    else
      send_data(get_query_data(params[:user_id]), filename: "#{user.name.gsub(/\s+/, "_")}_data.csv")
    end
      
  end

  def admin_login
    if( not session[:admin_id].nil? )
      redirect_to scholar_queries_path
    else
      render :login
    end
  end

  def admin_login_check
    a = Admin.all.where(name: params[:admin][:name]).first
    if(!a.nil? and a.authenticate params[:admin][:password])
      session[:admin_id] = a.id
      redirect_to scholar_queries_path
    else
      redirect_to "/login", notice: "Wrong name or password!"
    end
  end

  def admin_logout
    session[:admin_id] = nil
    redirect_to "/login"
  end

  private

    def get_query_data(user_id)
      user = User.find(user_id)
      queries = user.scholar_queries
      
      data = ""
      queries.each do |query|
        data += "#{query.query_text},#{query.created_at},#{query.satisfaction_str},#{query.broadness_str}\n"
      end

      return data

    end

    def get_query_scroll_behavior(user_id)
      queries = User.find(user_id).scholar_queries
      data = ""
      query_counter = 0
      
      queries.each do |query|
        data += "#{query.query_text},t#{query_counter}\n"
        query.query_scrolls.each do |scroll|
          data += "#{scroll.location},#{scroll.scroll_time}\n"
        end
      end

      return data
    end

    def get_query_clicks_data(user_id, timings)
      user = User.find(user_id)

      data = ""

      queries = user.scholar_queries
      query_clicks = {}
      query_counter = 0
      queries.each do |query|
        query_clicks[query.id] = 0
        if(timings)
          data += "#{query.query_text},t#{query_counter},#{query.broadness_str},#{query.satisfaction_str}"
        else
          data += "#{query.query_text},"
        end
        query_counter = query_counter + 1
      end

      data = data[0,data.length-1]
      data += "\n"

      for round in 1..40
        round_values = ""

        queries.each do |query|
          
          click_time = "-1"

          if( not QueryClick.where(scholar_query_id: query.id, location: round).empty? )
            query_clicks[query.id] = query_clicks[query.id] + 1
            click_time = QueryClick.where(scholar_query_id: query.id, location: round).first.created_at.to_s
          end
          if(timings)
            round_values += "#{query_clicks[query.id].to_s},#{click_time},"
          else
            round_values += "#{query_clicks[query.id].to_s},"
          end
        end

        data += round_values[0,round_values.length-1]
        data += "\n"
      end

      return data

    end

    def check_admin
      if not is_admin?
        redirect_to "/login"
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :token)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="page-header">
  <h1>Users
    <%= link_to raw("<i class='fa fa-plus'></i> New user"), new_user_path, class: "btn btn-success pull-right" %>
  </h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Task reports</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= link_to user.get_url, user.get_url %></td>
        <td><span class="badge"><%= user.task_reports.count %></span></td>
        <td><%= link_to raw("<i class='fa fa-times'></i> Remove this user"), user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/login.html.erb
<div class="page-header">
	<h1>Log in</h1>
</div>
<% if notice %>
	<div class="alert alert-danger">
		<%= notice %>
	</div>
<% end %>
<%= form_tag "login", method: :post do %>
	<div class="form-group">
		<%= label_tag "Name" %>
		<%= text_field_tag "admin[name]", "", class: "form-control" %>
	</div>
	<div class="form-group">
		<%= label_tag "Password" %>
		<%= password_field_tag "admin[password]", "", class: "form-control" %>
	</div>
	<div class="form-group">
		<%= submit_tag "Log in", class: "btn btn-primary" %>
	</div>
<% end %>

app/views/users/new.html.erb
<div class="page-header">
	<h1>New user</h1>
</div>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <h1><%= @user.name %>
    <small>
      <%= link_to @user.get_url, @user.get_url %>
    </small>
  </h1>
</div>
<h2>Download zip</h2>
<div class="well">
  <%= form_tag "/zip/#{@user.id}", method: :post do %>
    <div class="radio">
       <label>
          Clicks no time
          <%= radio_button_tag "content", "clicks_no_time", true %>
      </label>
    </div>
    <div class="radio">
       <label>
          Clicks with time
         <%= radio_button_tag "content", "clicks_with_time" %>
      </label>
    </div>
    <div class="radio">
      <label>
        Queries
         <%= radio_button_tag "content", "queries" %>
      </label>
    </div>
    <div class="radio">
      <label>
        Scroll
         <%= radio_button_tag "content", "scroll" %>
      </label>
    </div>
    <div class="radio">
      <label>
        Summaries
         <%= radio_button_tag "content", "summaries" %>
      </label>
    </div>
    <%= button_tag type: "submit", class: "btn btn-primary" do %>
      <i class="fa fa-download"></i> Download zip
    <% end %>
  <% end %>
</div>
<h2><%= pluralize(@user.task_reports.count, "task report") %></h2>
<div class="panel-group" id="accordion">
<% @user.task_reports.order(started: :desc).each do |report| %>
  <div class="panel panel-default">
    <div class="panel-heading"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse-<%= report.id %>"><i class="fa fa-file-text marg-right"></i><%= report.task.title %></a> <small>started at <%= report.started %></small></h4></div>

    <div id="collapse-<%= report.id %>" class="panel-collapse collapse">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-5">
              <h3 style="margin-top: 0px">Report</h3>
              <%= report.report %>
          </div>
          <div class="col-md-7">
            <div class="row">
                <div class="col-md-6">
                  <div class="well well-sm">
                    <h3 style="margin-top: 0px">Information</h3>
                     <dl style="margin-bottom: 0px">
                        <dt>Started at</dt>
                        <dd><%= report.started || report.created_at %></dd>
                        <dt>Completed at</dt>
                        <dd><%= report.completed %></dd>
                        <dt>Duration</dt>
                        <dd><%= report.duration %></dd>
                      </dl>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="well well-sm">
                   <h3 style="margin-top: 0px">Download data</h3>
                     <%= form_tag "/download_task_report/#{report.id}", method: :post do %>
                        <%= hidden_field_tag "task_report_id", report.id %>
                        <div class="radio">
                           <label>
                              Summary
                              <%= radio_button_tag "include", "summary", true %>
                          </label>
                        </div>
                        <div class="radio">
                           <label>
                            Query clicks without timings
                             <%= radio_button_tag "include", "clicks" %>
                          </label>
                        </div>
                        <div class="radio">
                          <label>
                            Queries with timings
                             <%= radio_button_tag "include", "queries" %>
                          </label>
                        </div>
                        <%= button_tag type: "submit", class: "btn btn-primary" do %>
                          <i class="fa fa-download"></i> Download data
                        <% end %>
                      <% end %>
                  </div>
                </div>
            </div>
          </div>
        </div>
        
        <%= link_to raw("<i class='fa fa-times'></i> Remove this report"), "/task_reports/#{report.id}", method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>

        <hr>

        <h3>Queries</h3>

        <table class="table table-striped" style="margin-bottom: 0px">
          <thead>
            <tr>
              <th>Query</th>
              <th>Time</th>
              <th>Click timings</th>
              <th>Scroll behavior</th>
              <th>Clicks</th>
            </tr>
          </thead>

          <tbody>
            <% report.scholar_queries.order(query_time: :desc).each do |scholar_query| %>
              <tr>
                <td><%= link_to scholar_query.query_text, scholar_query_path(scholar_query) %></td>
                <td><%= scholar_query.query_time || scholar_query.created_at %></td>
                <td><%= link_to raw('<i class="fa fa-download marg-right"></i>download'), "/download_query_clicks/#{scholar_query.id}", class: 'btn btn-default btn-sm'; %></td>
                <td><%= link_to raw('<i class="fa fa-download marg-right"></i>download'), "/download_query_scroll_behavior/#{scholar_query.id}", class: 'btn btn-default btn-sm'; %></td>
                <td><span class="badge"><%= scholar_query.query_clicks.count %></span></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/users/user_created.html.erb
<div class="page-header">
	<h1>New user created!</h1>
</div>
<p>
	New user can start at this url: <%= @search_url %>
</p>