config/routes.rb
GoogleScholarTragger::Application.routes.draw do
  
  resources :tasks

  resources :users, only: [:show, :index, :create, :new, :destroy]

  resources :query_clicks, only: [:create]

  resources :scholar_queries, only: [:create, :destroy, :show, :index]

  post "/zip/:user_id", to: "users#download_zip"
 
  get "/login", to: "users#admin_login"
  post "/download_user_data", to: "users#download_data"
  get "/", to: "users#admin_login"
  post "/login", to: "users#admin_login_check"
  post "/logout", to: "users#admin_logout"

  get "/search/:token", to: "api#user_search"
  post "/query", to: "api#scholar_query"
  
  post "/feedback", to: "scholar_queries#feedback"
  get "/download_query_clicks/:query_id", to: "scholar_queries#download_clicks_timings"
  get "/download_query_scroll_behavior/:query_id", to: "scholar_queries#download_scroll_behavior"

  post "/query_scroll", to: "query_scrolls#create"

  post "/task_reports", to: "task_reports#create"
  post "/send_task_report", to: "task_reports#update"
  post "/download_task_report/:task_report_id", to: "task_reports#download_task_report"
  delete "/task_reports/:id", to: "task_reports#destroy"

  get "/users_tasks", to: "tasks#users_tasks"

  post "/query_click_end", to: "query_clicks#query_click_end"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Search</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div class="wrapper">
		<% if not session[:admin_id].nil? %>
			<div class="navbar navbar-default navbar-fixed-top">
			  <div class="navbar-header">
			    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			    </button>
			    <div class="navbar-brand">Admin panel</div>
			  </div>
			  <div class="navbar-collapse collapse navbar-responsive-collapse">
			    <ul class="nav navbar-nav">
			      	<li><%= link_to "Queries", scholar_queries_path %></li>
			  	  	<li><%= link_to "Users", users_path %></li>
			  	  	<li><%= link_to "Tasks", tasks_path %></li>
			    </ul>
			    <%= form_tag "/logout", method: :post, class: "navbar-form navbar-right" do %>
		        	<%= button_tag type: "submit", class: "btn btn-primary" do %>
		        		<i class="fa fa-sign-out"></i> Log out
		        	<% end %>
		        <% end %>
		      	</form>
			  </div>
			</div>
		<% end %>
		<%= yield %>
	</div>
</div>
</body>
</html>